translate Japanese strings:
    old "Ghost Under the Light"
    new "燈の下の幽霊"

    old "The tendrils of my hair illuminate beneath the amber glow.\nBathing.\nIt must be this one.\nThe last remaining streetlight to have withstood the test of time.\nthe last yet to be replaced by the sickening blue-green hue of the future.\nI bathe. Calm; breathing air of the present but living in the past.\nThe light flickers.\nI flicker back."
    new "絡みつく私の髪が琥珀色の燈に照らされる。\nひたり。\nまさにこれだ。\n時という試練に耐え続けた最後の街燈。\nいつかは病的な青緑の色調に置き換わる、最後の。\nひたる。閑かに……現代の空気を吸いつつも過去に息づく。\n明滅する燈。\n私も明滅と同調する。"

















    old "The Raccoon"
    new "アライグマ"

    old "It happened in the dead of night while I was slicing bread for a guilty snack.\nMy attention was caught by the scuttering of a raccoon outside my window.\nThat was, I believe, the first time I noticed my strange tendencies as an unordinary human.\nI gave the raccoon a piece of bread, my subconscious well aware of the consequences.\nWell aware that a raccoon that is fed will always come back for more.\nThe enticing beauty of my cutting knife was the symptom.\nThe bread, my hungry curiosity.\nThe raccoon, an urge.\nThe moon increments its phase and reflects that much more light off of my cutting knife.\nThe very same light that glistens in the eyes of my raccoon friend.\nI slice the bread, fresh and soft. The raccoon becomes excited.\nOr perhaps I'm merely projecting my emotions onto the newly-satisfied animal.\nThe raccoon has taken to following me.\nYou could say that we've gotten quite used to each other.\nThe raccoon becomes hungry more and more frequently, so my bread is always handy.\nEvery time I brandish my cutting knife, the raccoon shows me its excitement.\nA rush of blood. Classic Pavlovian conditioning. I slice the bread.\nAnd I feed myself again."
    new "それは真夜中、密かな楽しみにと軽食のパンを切っていた時のことでした。\n窓の向こうに時折ちらつくアライグマが、私の目に付きました。\n自分が異質な人間であると気付いたのは、おそらくこれが初めてだったのでしょう。\nどのような結末を招くか解っていながらも、私はパンをひとかけらアライグマに与えます。\n餌付けされたアライグマは必ずまたやって来ると解っていながら。\n蠱惑するナイフが症状でした。\nパンは、私の飢えた好奇心。\nアライグマは、衝動。\n月は満ち、私のナイフはいちだんと眩い光を湛えます。\n友達アライグマの目を輝かせるのは、まさしくその光。\n出来立てで柔らかいパンを切る。逸るアライグマ。\nもしや、再び満ち足りた獣に私の感情を投影しているだけなのかしら。\nアライグマは私にすっかり懐いてしまいました。\nお互いよく知る関係になれたのではないでしょうか。\nアライグマはしょっちゅうお腹を空かせるので、パンが欠かせません。\n私のナイフを見せるたび、アライグマは興奮します。\n血の滾り。パブロフ型の古典的条件付け。パンを切って。\nそしてまた私に餌付けるの。"





































    old "Beach"
    new "砂浜"

    old "A marvel millions of years in the making.\nWhere the womb of Earth chaotically meets the surface.\nUnder a clear blue sky, an expanse of bliss--\nBut beneath gray rolling clouds, an endless enigma.\nThe easiest world to get lost in\nIs one where everything can be found.\nOne can only build a sand castle where the sand is wet.\nBut where the sand is wet, the tide comes.\nWill it gently lick at your foundations until you give in?\nOr will a sudden wave send you crashing down in the blink of an eye?\nEither way, the outcome is the same.\nYet we still build sand castles.\nI stand where the foam wraps around my ankles.\nWhere my toes squish into the sand.\nThe salty air is therapeutic.\nThe breeze is gentle, yet powerful.\nI sink my toes into the ultimate boundary line, tempted by the foamy tendrils.\nTurn back, and I abandon my peace to erode at the shore.\nDrift forward, and I return to Earth forevermore."
    new "気の遠くなるような遠い昔から。\n大地の内と外が混ざり続けている場所。\n青空の下、喜びが満ち溢れ――\n灰色の雲が落とすのは、解けない暗号。\nすぐに道を見失ってしまう世界では、\n全てを見つけることだってできるはず。\nお城が作れるのは砂の湿ったところ。\nでもそれは潮の来るところ。\n諦めるまで少しずつ、優しく壊してくれる？\nそれとも瞬きしている間に一気に奪ってしまう？\nどちらだって結果は同じ。\nそれでも人は砂のお城を作るのをやめないの。\n浜辺に立つ私の足は泡に濡れて。\n足先が砂に沈んでいく。\n心地良い潮の香り。\n吹きつける潮風は優しく、力強い。\n絡みつく泡をもっと感じたくて、私はどこまでも砂を踏みしめる。\n我に返って、浜辺を荒らす遊びをやめたら。\n前を向いて、私は陸に戻る。永遠に。"







































    old "Ghost Under the Light pt. 2"
    new "燈の下の幽霊　２"

    old "The tendrils of my hair illuminate beneath the amber glow.\nBathing.\nIn the distance, a blue-green light flickers.\nA lone figure crosses its path - a silhouette obstructing the eerie glow.\nMy heart pounds. The silhouette grows. Closer. Closer.\nI open my umbrella, casting a shadow to shield me from visibility.\nBut I am too late.\nHe steps into the streetlight. I gasp and drop my umbrella.\nThe light flickers. My heart pounds. He raises his arm.\nTime stops.\nThe only indication of movement is the amber light flickering against his outstretched arm.\nThe flickering light is in rhythm with the pounding of my heart.\nTeasing me for succumbing to this forbidden emotion.\nHave you ever heard of a ghost feeling warmth before?\nGiving up on understanding, I laugh.\nUnderstanding is overrated.\nI touch his hand. The flickering stops.\nGhosts are blue-green. My heart is amber."
    new "絡みつく私の髪が琥珀色の燈に照らされる。\nひたり。\n遠くには、明滅する青緑の燈。\n一つの人影が道を横切り――影はその不気味な輝きを遮断する。\n心臓が早鐘を打つ。影が伸びる。こっちに。こっちに。\n陰を落とし視界を遮るように、私は傘を差す。\nだが遅すぎた。\n街燈に踏み入る彼。私は息を呑み、傘を取り落とす。\n燈は明滅する。心臓が早鐘を打つ。彼が腕を持ち上げる。\n時が止まる。\n琥珀色の燈の明滅だけが、広げる彼の腕の揺れを投影する。\n明滅する燈と早鐘を打つ私の心臓とが、リズムを重ねる。\nこの禁断の感情に屈するために、私をいじめて。\n幽霊が温かい心地になるなんて、聞いたことあるかしら？\n理解を諦め、私は哂う。\n理解なんてしていられない。\n彼の手に触れる。明滅が止む。\n青緑色の幽霊。私の、琥珀色の心臓。\n"






































    old "Wheel"
    new "車輪"

    old "A rotating wheel. Turning an axle. Grinding. Bolthead. Linear gearbox. Falling sky. Seven holy stakes. A docked ship. A portal to another world. A thin rope tied to a thick rope. A torn harness. Parabolic gearbox. Expanding universe. Time controlled by slipping cogwheels. Existence of God. Swimming with open water in all directions. Drowning. A prayer written in blood. A prayer written in time-devouring snakes with human eyes. A thread connecting all living human eyes. A kaleidoscope of holy stakes. Exponential gearbox. A sky of exploding stars. God disproving the existence of God. A wheel rotating in six dimensions. Forty gears and a ticking clock. A clock that ticks one second for every rotation of the planet. A clock that ticks forty times every time it ticks every second time. A bolthead of holy stakes tied to the existence of a docked ship to another world. A kaleidoscope of blood written in clocks. A time-devouring prayer connecting a sky of forty gears and open human eyes in all directions. Breathing gearbox. Breathing bolthead. Breathing ship. Breathing portal. Breathing snakes. Breathing God. Breathing blood. Breathing holy stakes. Breathing human eyes. Breathing time. Breathing prayer. Breathing sky. Breathing wheel."
    new "回転する車輪。車軸を自転。研削。ボルトヘッド。線状の変速装置。落ちる空。七本の聖なる杭。 泊まっている船。異世界へのポータル。太い縄に縛られた細い縄。引き裂かれた馬具。放物変速装置。 拡大する宇宙。時間を取り締まる滑り歯車。神の存在。四方八方公海で水泳。 溺水。血で書いた祈り。人間の目を持った時間を食い荒らす蛇で書いた祈り。 全ての生きる目を繋ぐ糸。聖なる杭の万華鏡。指数的変速装置。 爆裂する星の空。神が神の存在を反証。六次元に回転する車輪。 四十の歯車と時計。惑星を回転するごとに一秒を進める時計。 隔回を進めるごとに四十回を進める時計。異世界への泊まっている 船に繋いだ聖なる杭のボルトヘッド。時計で書いた血の万華鏡。 四十の歯車と 開いた人間の目四方八方に繋いだ時間を食い荒らす祈り。息吹く変速装置。息吹くボルトヘッド。 息吹く船。息吹くポータル。息吹く蛇。息吹く神。息吹く血。息吹く聖なる杭。 息吹く人間の目。息吹く時間。息吹く祈り。息吹く空。息吹く車輪。"

























    old "mdpnfbo,jrfp"
    new "mdpnfbo,jrfp"

    old "ed,,zinger suivante,,tels handknits finish,,cagefuls basinlike bag octopodan,,imbossing vaporettos rorid easygoingnesses nalorphines,,benzol respond washerwomen bristlecone,,parajournalism herringbone farnarkeled,,episodically cooties,,initiallers bimetallic,,leased hinters,,confidence teetotaller computerphobes,,pinnacle exotically overshades prothallia,,posterior gimmickry brassages bediapers countertrades,,haslet skiings sandglasses cannoli,,carven nis egomaniacal,,barminess gallivanted,,southeastward,,oophoron crumped,,tapued noncola colposcopical,,dolente trebbiano revealment,,outworked isotropous monosynaptic excisional moans,,enterocentesis jacuzzi preoccupations,,hippodrome outward googs,,tabbises undulators,,metathesizing,,sharia prepostor,,neuromast curmudgeons actability,,archaise spink reddening miscount,,madmen physostigmin statecraft neurocoeles bammed,,tenderest barguests crusados trust,,manshifts darzis aerophones,,reitboks discomposingly,,expandors,,monotasking galabia,,pertinents expedients witty,,chirographies crachach unsatisfactoriness swerveless,,flawed sepulchred thanksgiver scrawl skug,,perorate stringers gelatine flagstones,,chuses conceptualization surrejoined,,counterblasts rache,,numerative,,delirifacients methylthionine,,mantram dynamist atomised,,eternization percalines hryvnias pragmatizing,,reproachfulnesses telework nowts demoded revealer,,burnettize caryopteris subangular wirricows,,transvestites sinicized narcissus,,hikers meno,,degassing,,postcrises alikenesses,,sycophancy seroconverting insure,,yantras raphides cliftiest bosthoon,,zootherapy chlorides nationwide schlub yuri,,timeshares castanospermine backspaces reincite,,coactions cosignificative palafitte,,poofters subjunctions,,aquarian,,theralite revindicating,,cynosural permissibilities narcotising,,journeywork outkissed clarichords troutier,,myopias undiverting evacuations snarier superglue,,deaminise infirmaries teff hebephrenias,,brainboxes homonym lancelet,,lambitive stray,,inveigled,,acetabulums atenolol,,dekkos scarcer flensed,,abulias flaggers wammul boastfully,,galravitch happies interassociation multipara augmentations,,teratocarcinomata coopting didakai infrequently,,hairtails intricacy usuals,,pillorise outrating,,cataphoresis,,furnishings leglen,,goethite deflate butterburs,,phoneticising winiest hyposulphuric campshirts,,chainfalls swimmings roadblocked redone soliloquies,,broking mendaciousness parasitisms counterworld,,unravellings quarries passionately,,onomatopoesis repenting,,ramequin,,mopboard euphuistically,,volta sycophantized allantoides,,bors bouclees raisings sustaining,,diabolist sticks dole liltingly,,curial bisexualisms siderations hemolysed,,damnabilities unkenneling halters,,peripheral congaing,,diatomicity,,foolings repayments,,hereabouts vamosed him,,slanters moonrock porridgy monstruous,,heartwood bassoonist predispositions jargoon dominances,,timidest inalienable rewearing inevitably,,entreating retiary tranquillizing,,uniparental droogs,,allotropous,,forzati abiogenetic,,obduration exempted unifaces,,epilating calisaya dispiteously coggles,,vestmented flukily ignifying complished hiccupy municipalize,,pentagraphs parcels sutler excavates,,stardust miscited thankfulness,,fouter pertused,,overpacks,,guarishes hylotheism,,pi\nFresh blood seeps through the line parting her skin and slowly colors her breast red. I begin to hyperventilate as my compulsion grows. The images won’t go away. Images of me driving the knife into her flesh continuously, fucking her body with the blade, making a mess of her. My head starts going crazy as my thoughts start to return. Shooting pain assaults my mind along with my thoughts. This is disgusting. Absolutely disgusting. How could I ever let myself think these things? But it’s unmistakable. The lust continues to linger through my veins. An ache in my muscles stems from the unreleased tension experienced by my entire body. Her Third Eye is drawing me closer."
    new "た，，言葉のとげ  御次，，TEL達  手編  終了，，肌理細達  水盤の張る  かばん  八腕類，，浮きえりつく  ヴァポレット達  露型  安閑達  ナロルフィン達，，ベンゾール  答酬  洗濯女達  球果にとげ，，パラジャーナリズム  杉綾模様  ファーナークルした，，挿話的  しらみ達，，へん首者達  バイメタル，，専用の  暗示者達，，信頼  絶対禁酒者  コンピューター恐怖症達，，尖塔  エキゾチック愛してる  曇らせる  前葉体，，項部  絡繰り  貨幣鋳造費達  御湿替え達  等価交換達，，ホルモン  スキー達  砂時計達  カンノーリ，，彫刻した  ボギー  自己愛人格，，泡立って  いちゃつかれた，，言い寄られた，，卵巣  狭苦しい，，タプだった  非コーラ  ちつ鏡的，，愁然  トレッビアーノ  顕正，，在宅ワークした  等方的  モノシナプチック  削除的  呻く，，移植臓器  気泡風呂  占取達，，競馬場  外形的  卵，，綾絹達  波打つ人達，，複分解し，，シャリーア  生徒会長，，神経細胞帆柱  頑固親父達  行為可能，，古風にする  ズアオアトリ  赤らみ  数え違える，，狂人達  フィゾスチグミン  国政  脊柱管  ドンした，，一番柔らかい  バー客達  クルザード  信頼，，マンシフト  裁縫師達  気鳴楽器，，リードバック達  腐らんの用に，，拡大者達，，  モノタスキング  ジッラーバ，，合目的的達  方便  軽妙，，書法達  クラチャチャ  物足りない  逸れない，，欠陥  葬った  感謝祭者  金くぎ流  片陰，，言い募る  側桁達  ゼラチン  板石，，撰ぶ  通訳  後退した，，カウンターブラスト  狩猟犬，，数値的，，振戦せん妄  メチルチオニン，，明呪  ダイナミズト  勦討した，，永遠化  パーカルライン  フリヴニャ  実際的になる，，反抗的達  テレワーク  絶無達  野暮ったい  啓示者，，バーネットするカリガネソウ属  副鋭角的  小悪魔達，，女装趣味の男性達  中国系  水仙，，  ハイカー  達  メノ，，脱気，，危機後  相似，，ごま擂り  セロコンバージョン  保険を掛ける，，ヤントラ  ドードー科至福の  ボストゥーン，，動物療法  塩化物  全国的  シュバルツ  ユリ，，タイムシェア  カスタノスペルミン  バックスペース  レインケイト，，連合  意識的  パラフィット，，プフター  サブジャンクション，，水族館，，テラライト  再表示する，，こぐま座的  許容達  麻薬をかけう，，ジャーニーワーク  アウトキスした  クラリコード  もっとマス，，近視  不転換的  撤退  もっとなわ網  強力接着剤，，デアミナーゼ  診療所  テフ  破瓜病，，脳箱達  同音異義語  頭索動物達，，リンクチュール  迷走，，転換した，，寛骨臼  アテノロール，，デッコ達  もっと希少  羊毛を刈った，，アブリア旗を立てる人達  ワンムル  自慢たらしげに，，ガルラヴィッチ  嬉しい達  国際協会  マルチパラ    オーグメンテイション，，奇形腫達  互選  ジダカイ  低頻度に，，タチウオ科  煩雑  通常達，，さらし台  格付き勝つ，，電気泳動，，備品  レグレン，，針鉄鉱  萎む  蜂斗菜属，，音声学的に書く  一番ワイン  低硫酸の  キャンプシャツ，，鎖の墜落達  水泳達  道路封鎖した    やり直した  独り言，，仲買  不正直  寄生達  カウンターワールド，，解きほぐすこと  採石場達  怒りを込めて，，オノマトペ  悔い改めること，，ラメキン，，モップボード  ユーフイスム的に，，ボルタ  ごま磨りした  尿膜，，ボルス  バックル  飼育達  持続，，悪魔の崇拝者  棒達  布施  軽快に，，司教顧問会的  両性的  側配給達  溶血した，，責めりの可能性  不犬小屋すること  平均こん，，  ペリフェラル    コンガすること，，二原子，，だまし達  返金達，，このあたりに  ヴァモスした  彼を，，傾斜者達  ムーンストーン  かゆの様な  醜怪な，，ハートウッド  バスーニスト  前配置  隠語  優性，，一番気弱  疎めない  もう一度着る  必然，，懇願する  網闘士  鎮静剤，，片親的  与太者達，，同素体の，，フォーザート  不生物工的，，猛烈にする  免じた  ユニフェイス，，脱毛  カリサヤ  凶悪性的に  コグレス，，法衣した  紛れように火を掛ける  成し遂げた  しゃっくり  局地にする，，五字熟語  小包  サトラー  掘削する，，星屑  不正解の引用  有難さ，，下劣な人  突き刺した，，オーバーパックス，，癒す  ヒロセイズム，，円周率\n鮮血が彼女の身体を分けるようににじみ出し、ゆっくりと彼女の胸を赤く染める。脅迫感が増すにつれ、私の息は荒くなる。  イメージが頭から離れない。  ナイフを立て続けに彼女の肉に走らせ、その体を刃でじゅうりんするイメージが、彼女を混乱させる。  思考が戻り始めるとともに、狂いだす。  私の思考と一緒に、刺すような痛みが私の心を襲う。  嫌だ。  絶対に嫌だ。  どうやって私自身こんなことを考えられたんだ？  だが間違いない。  欲望は私の脈に残っている。  私の筋肉の痛みは、体中が経験した未知の緊張によって始まる。  彼女の第三の目は、私を引き込ませている。"

































































































    old "Eagles Can Fly"
    new "ワシは飛べる"

    old "Monkeys can climb\nCrickets can leap\nHorses can race\nOwls can seek\nCheetahs can run\nEagles can fly\nPeople can try\nBut that's about it."
    new "サルは登れる\nコオロギは飛び跳ねられる\nウマは駆けっこできる\nフクロウは見つけられる\nチーターは走れる\nワシは飛べる\nヒトは努力できる\nだけどそれくらい。"

















    old "Amy Likes Spiders"
    new "エイミーはクモが好き"

    old "You know what I heard about Amy?\nAmy likes spiders.\nIcky, wriggly, hairy, ugly spiders!\nThat's why I'm not friends with her.\nAmy has a cute singing voice.\nI heard her singing my favorite love song.\nEvery time she sang the chorus, my heart would pound to the rhythm of the words.\nBut she likes spiders.\nThat's why I'm not friends with her.\nOne time, I hurt my leg really bad.\nAmy helped me up and took me to the nurse.\nI tried not to let her touch me.\nShe likes spiders, so her hands are probably gross.\nThat's why I'm not friends with her.\nAmy has a lot of friends.\nI always see her talking to people.\nShe probably talks about spiders.\nWhat if her friends start to like spiders too?\nThat's why I'm not friends with her.\nIt doesn't matter if she has other hobbies.\nIt doesn't matter if she keeps it private.\nIt doesn't matter if it doesn't hurt anyone.\nIt's gross.\nShe's gross.\nThe world is better off without spider lovers.\nAnd I'm gonna tell everyone."
    new "エイミーのこと聞いた？\nエイミーはクモが好き。\nべとべと、もぞもぞ、もじゃもじゃでキモイあのクモが！\nだからわたしは友達にならないの。\nエイミーの歌声はかわいい。\nわたしのお気に入りのラブソングを歌ってたな。\nサビを歌うといつも、歌詞のリズムにあわせて心がどきどきした。\nでもあの子はクモが好き。\nだからわたしは友達にならないの。\nいちど、足を大ケガしたこともあったな。\nエイミーが保健室に行くのを手伝ってくれた。\nわたしはあの子にさわらないようにした。\nあの子はクモが好きで、手もキモそうだったし。\nだからわたしは友達にならないの。\nエイミーには友達がたくさん。\nいつもだれかしらと話してる。\nたぶんクモについて話してるんじゃないかな。\nもしあの子の友達もクモが好きになっちゃったら？\nだからわたしは友達にならないの。\n他に好きなものがあったって知るもんか。\nひみつにしてたって知るもんか。\n傷つく人がいなくたって知るもんか。\nキモイんだ。\nあの子はキモイんだ。\n世界にクモ好きの人なんていない方がいいんだ。\nだからみんなに話しちゃお。"





















































    old "T3BlbiBZb3VyIFRoaXJkIEV5ZQ=="
    new "56ys5LiJ44Gu55uu44KS6ZaL44GR"

    old "SSBjYW4gZmVlbCB0aGUgdGVuZGVybmVz\ncyBvZiBoZXIgc2tpbiB0aHJvdWdoIHRo\nZSBrbmlmZSwgYXMgaWYgaXQgd2VyZSBh\nbiBleHRlbnNpb24gb2YgbXkgc2Vuc2Ug\nb2YgdG91Y2guIE15IGJvZHkgbmVhcmx5\nIGNvbnZ1bHNlcy4gVGhlcmUncyBzb21l\ndGhpbmcgaW5jcmVkaWJseSBmYWludCwg\nZGVlcCBkb3duLCB0aGF0IHNjcmVhbXMg\ndG8gcmVzaXN0IHRoaXMgdW5jb250cm9s\nbGFibGUgcGxlYXN1cmUuIEJ1dCBJIGNh\nbiBhbHJlYWR5IHRlbGwgdGhhdCBJJ20g\nYmVpbmcgcHVzaGVkIG92ZXIgdGhlIGVk\nZ2UuIEkgY2FuJ3QuLi5JIGNhbid0IHN0\nb3AgbXlzZWxmLg=="
    new "44OK44Kk44OV6LaK44GX44Gr44CB5b28\n5aWz44Gu5p+U6IKM44KS44GC44Gf44GL\n44KC6Ieq5YiG44Gu6Kem6Kaa44Gu5bu2\n6ZW344Gn5pyJ44KL44GL44Gu44KI44GG\n44Gr5oSf44GY5Y+W44KL44GT44Go44GM\n44Gn44GN44KL44CC56eB44Gv6Lqr5oK2\n44GI44GZ44KL44CC44GT44Gu5omL44Gr\n6LKg44GI44Gq44GE44G744Gp44Gu5b+r\n5qW944Gr5oqX44GK44GG44Go5L2V44GL\n44GM44CB44Gy44Gp44GP5b6u44GL44Gn\n44GC44KL44GM5aWl5bqV44Gn5Y+r44KT\n44Gn44GE44KL44CC44Gd44KM44Gn44KC\n44CB5pei44Gr54uC5rCX44Gr5L6144GV\n44KM44Gm44GE44KL44Gu44KS6Ieq6Kaa\n44GX44Gm44GE44KL44CC56eB44Gv4oCm\n4oCm6Ieq5YiG44KS5oqR44GI44KJ44KM\n44Gq44GE44CC"
































    old "I'll Be Your Beach"
    new "あなたの砂浜になる"

    old "Your mind is so full of troubles and fears\nThat diminished your wonder over the years\nBut today I have a special place\nA beach for us to go.\nA shore reaching beyond your sight\nA sea that sparkles with brilliant light\nThe walls in your mind will melt away\nBefore the sunny glow.\nI'll be the beach that washes your worries away\nI'll be the beach that you daydream about each day\nI'll be the beach that makes your heart leap\nIn a way you thought had left you long ago.\nLet's bury your heavy thoughts in a pile of sand\nBathe in sunbeams and hold my hand\nWash your insecurities in the salty sea\nAnd let me see you shine.\nLet's leave your memories in a footprint trail\nSet you free in my windy sail\nAnd remember the reasons you're wonderful\nWhen you press your lips to mine.\nI'll be the beach that washes your worries away\nI'll be the beach that you daydream about each day\nI'll be the beach that makes your heart leap\nIn a way you thought had left you long ago.\nBut if you let me by your side\nYour own beach, your own escape\nYou'll learn to love yourself again."
    new "あなたの心は不安と恐れに満ち満ちて\nこの数年で魅力も褪せてしまった\nでも今日はとっておきの場所にいこう\nわたしとあなたの砂浜へ。\n見渡すかぎりいちめんの岸\n艶やかな光をはなつ海\nそんなまばゆさの前なら\nあなたの心の壁も崩れてしまうよ。\nわたしは悩みを洗い流す砂浜になる\nあなたがいつも訪れる白昼夢の砂浜になる\nこんなときめきをずっと忘れてたんだって\nあなたの心が弾むような砂浜になるよ。\n重苦しい気分は砂の山に埋めてしまおう\n陽ざしを浴びて手をつなごう\nとまどいをしょっぱい海で洗ったら\nキラキラ光るあなたを見せて。\n思い出は足あとの道に残していこう\n帆に風をつかんで自由になろう\nあなたとわたしの唇を重ねたら\nあなたが素敵なわけを思い出して。\nわたしは悩みを洗い流す砂浜になる\nあなたがいつも訪れる白昼夢の砂浜になる\nこんなときめきをずっと忘れてたんだって\nあなたの心が弾むような砂浜になるよ。\nわたしを隣にいさせてくれれば、あなたは\n自分だけの砂浜、自分だけの出口で\nまた自分を愛せるようになるはずだから。"























































    old "Because You"
    new "あなたが"

    old "Tomorrow will be brighter with me around\nBut when today is dim, I can only look down.\nMy looking is a little more forward\nBecause you look at me.\nWhen I want to say something, I say it with a shout!\nBut my truest feelings can never come out.\nMy words are a little less empty\nBecause you listen to me.\nWhen something is above me, I reach for the stars.\nBut when I feel small, I don't get very far.\nMy standing is a little bit taller\nBecause you sit with me.\nI believe in myself with all of my heart.\nBut what do I do when it's torn all apart?\nMy faith is a little bit stronger\nBecause you trusted me.\nMy pen always puts my feelings to the test.\nI'm not a good writer, but my best is my best.\nMy poems are a little bit dearer\nBecause you think of me.\nBecause you, because you, because you."
    new "明日はきっといい日\nでも今日はだめ、下を向いてばかり。\nあなたが見つめてくれるなら\n少しはましな顔になれるよ。\n何かを言いたいとき、叫ばずにはいられない！\nでも本当の気持ちは全然こもってない。\nあなたが聞いてくれるなら\n少しは気持ちを込められるよ。\nふと夜空を見上げて、わたしは星に手を伸ばす。\nでもわたしは小さくて、どこにも手が届かない。\nあなたが隣にいてくれるなら\n少しは遠くまで届くよ。\nわたしは心から自分を信じてる。\nでも心が引き裂かれたらどうすればいいの？\nあなたが信じてくれるなら\n少しは強くなれるよ。\nペンを握るといつも試されてる気分。\nわたしは上手に書けない、これが精一杯。\nあなたがわたしのことを考えてくれるなら\n少しは良い詩が書けるよ。\nあなた、あなた、あなたが。"











































    old "I don't know how else to bring this up. But there's been something I've been worried about. Yuri has been acting kind of strange lately. You've only been here a few days, so you may not know what I mean. But she's not normally like this. She's always been quiet and polite and attentive...things like that.\nOkay... This is really embarrassing, but I'm forcing myself to suck it up. The truth is, I'm REALLY worried about her. But if I try talking to her, she'll just get mad at me again. I don't know what to do. I think you're the only person that she'll listen to. I don't know why. But please try to do something. Maybe you can convince her to talk to a therapist.\nI've always wanted to try being better friends with Yuri, and it really hurts me to see this happening. I know I'm going to hate myself later for admitting that, but right now I don't care. I just feel so helpless. So please see if you can do something to help. I don't want anything bad to happen to her. I'll make you cupcakes if I have to. Just please try to do something.\nAs for Monika... I don't know why, but she's been really dismissive about this. It's like she just wants us to ignore it. So I'm mad at her right now, and that's why I'm coming to you about this. DON'T LET HER KNOW I WROTE THIS!!!! Just pretend like I gave you a really good poem, okay? I'm counting on you. Thanks for reading."
    new "これ以外に伝える手段が思いつかない。でも最近心配していることがあるの。ユリの様子がおかしいの。あんたはまだ来て数日だから違いが分からないかもしれないけど。普段はあんな子じゃないの。いつもは落ち着いてて礼儀正しくて親切で……そんな感じの子。\nこれを言うのは恥ずかしいんだけど、勇気を振り絞って打ち明けるわ。ほんとはあいつがとにかく心配で仕方ないの。でも直接話そうとしても、きっとまた怒られるだろうから。どうすればいいのか分からない。\n今はあんたの言うことしか聞かないと思う。なんでかは分からない。でもお願いだからなんとかして。あんたなら心療内科にでも行くように説得できるかもしれない。ユリとはもっと仲良くなりたいってずっと思ってたから、こんなことになって見てて辛い。こんなこと打ち明けて後悔するだろうけど今はなんでもいい。とにかく無力なの。だから何かできるならお願い。あいつに何かあったら嫌なの。カップケーキならいくらでも作るから。お願いだからなんとかして。\nあとモニカは……なぜかこのことに否定的で。何もして欲しくないみたいで。だからあんなやつには頼めなくて、あんたを頼ってるの。絶 対 に あ い つ に こ の こ と が バ レ な い よ う に ！ ！ ！ ！ とにかくわたしがすごく良い詩を書いたようなフリをしてて。頼んだわよ。ここまで読んでくれてありがとう。"







































    old "Dear Sunshine"
    new "親愛なるお日様へ"

    old "The way you glow through my blinds in the morning\nIt makes me feel like you missed me.\nKissing my forehead to help me out of bed.\nMaking me rub the sleepy from my eyes.\nAre you asking me to come out and play?\nAre you trusting me to wish away a rainy day?\nI look above. The sky is blue.\nIt's a secret, but I trust you too.\nIf it wasn't for you, I could sleep forever.\nBut I'm not mad.\nI want breakfast."
    new "ブラインドから差し込む朝の陽ざしで、\nきみがさみしかったのがわかるよ。\n額にキスをしてくれるとベッドから起き上がれるの。\n目をごしごしして眠気をぬぐう。\n表に出てあそぼうって誘ってるの？\n雨ならいいのにって思ってないか確かめているの？\n上をあおぐ。真っ青な空。\nヒミツだけど、わたしもきみを信じてるよ。\nきみがいなきゃ、ずっと眠ってられるのにね。\nでも怒ってないよ。\nあさごはんたべたいな。"























    old "Bottles"
    new "ビン"

    old "I pop off my scalp like the lid of a cookie jar.\nIt's the secret place where I keep all my dreams.\nLittle balls of sunshine, all rubbing together like a bundle of kittens.\nI reach inside with my thumb and forefinger and pluck one out.\nIt's warm and tingly.\nBut there's no time to waste! I put it in a bottle to keep it safe.\nAnd I put the bottle on the shelf with all of the other bottles.\nHappy thoughts, happy thoughts, happy thoughts in bottles, all in a row.\nMy collection makes me lots of friends.\nEach bottle a starlight to make amends.\nSometimes my friend feels a certain way.\nDown comes a bottle to save the day.\nNight after night, more dreams.\nFriend after friend, more bottles.\nDeeper and deeper my fingers go.\nLike exploring a dark cave, discovering the secrets hiding in the nooks and crannies.\nDigging and digging.\nScraping and scraping.\nI blow dust off my bottle caps.\nIt doesn't feel like time elapsed.\nMy empty shelf could use some more.\nMy friends look through my locked front door.\nFinally, all done. I open up, and in come my friends.\nIn they come, in such a hurry. Do they want my bottles that much?\nI frantically pull them from the shelf, one after the other.\nHolding them out to each and every friend.\nEach and every bottle.\nBut every time I let one go, it shatters against the tile between my feet.\nHappy thoughts, happy thoughts, happy thoughts in shards, all over the floor.\nThey were supposed to be for my friends, my friends who aren't smiling.\nThey're all shouting, pleading. Something.\nBut all I hear is echo, echo, echo, echo, echo\nInside my head."
    new "クッキー缶のフタのように、頭をパカッと開ける。\nわたしの夢をぜんぶつめた、ヒミツの場所よ。\nちいさな日光のボールが集まって、子猫のようにすり寄ってくる。\n親指と人差し指とで、ひとつつまむ。\nあったかくて、ちくちくするの。\nでもうかうかしてられない！大切にビンにしまう。\nそのビンを、他のビンと同じように棚に置いていくんだ。\nビンが並ぶ、その中にはシアワセ、シアワセ、シアワセ。\nわたしのコレクションがともだちの輪を広げたよ。\nビンの中身は償いの星明かりになるの。\nともだちが何かを感じて仕方がないとき。\nこういうときにビンが役に立つのよ。\n夜な夜なの夢、ふくらんで。\nぞくぞくともだち、ビンは増える。\nわたしの指はより奥へ、奥へ。\nまるで、くらい洞窟の中でいたるところに隠されたヒミツを探るような。\n堀って、掘って。\n削って、削って。\nフタのホコリを吹き飛ばす。\nいつの間にか時が過ぎてる。\nもっといっぱいあったはずの、空っぽの棚。\nカギのかかったドアの向こうからともだちの視線を感じる。\nやっとできたよ。ドアを開けると、ともだちが入ってくる。\nドタドタと押し寄せる。そんなにビンがほしいの？\nわたしは必死に棚から次々とビンを取りだす。\nともだちひとりひとりに持たせていく。\nひとつひとつ、ぜんぶのビンを。\nだけど渡すたびに、足もとのタイルで粉々になっていく。\n床にぜんぶ、散らばるシアワセ、シアワセ、シアワセ。\nともだちの、笑わないともだちのためだったんだよ。\nみんなみんな叫んでいる。訴えている。何かを。\nただ聞こえるのは残響、残響、残響、残響、残響\nわたしの頭の中で。"



































































    old "%"
    new "%"

    old "Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of my head. Get out of\nGet.\nOut.\nOf.\nMy.\nHead.\n\n\n\nGet out of my head before I do what I know is best for you.\nGet out of my head before I listen to everything she said to me.\nGet out of my head before I show you how much I love you.\nGet out of my head before I finish writing this poem.\n\n\n\n\n\n\n\nBut a poem is never actually finished.\nIt just stops moving."
    new "わたしのあたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。あたまからでていけ。わたしの\nわたし。\nの。\nあたま。\nから。\nでていけ。\n\n\n\nあなたにとっていちばんのことをしてしまうまえにわたしのあたまからでていけ。\nあのこにいわれたことをぜんぶきいてしまうまえにわたしのあたまからでていけ。\nあなたへのあいをみせてしまうまえにわたしのあたまからでていけ。\nこのしをかきおえてしまうまえにわたしのあたまからでていけ。\n\n\n\n\n\n\n\nだけど詩に本当の終わりなんてない。\n動きを止めるだけ。"

























    old "Hole in Wall"
    new "壁の穴"

    old "It couldn't have been me.\nSee, the direction the spackle protrudes.\nA noisy neighbor? An angry boyfriend? I'll never know. I wasn't home.\nI peer inside for a clue.\nNo! I can't see. I reel, blind, like a film left out in the sun.\nBut it's too late. My retinas.\nAlready scorched with a permanent copy of the meaningless image.\nIt's just a little hole. It wasn't too bright.\nIt was too deep.\nStretching forever into everything.\nA hole of infinite choices.\nI realize now, that I wasn't looking in.\nI was looking out.\nAnd he, on the other side, was looking in."
    new "私の仕業じゃない。\nほら、補修材がこっちに突き出ているもの。\n口煩い隣人が？鬱憤の溜まった彼氏が？見当もつかない。私は家に居なかったし。\n手掛かりを求め中を覗く。\nしまった！何も見えない。陽に晒されたフィルムのように目が眩み、後ずさる。\nだが手遅れだった。網膜には。\n既に無意味な情景が焼き付いて離れない。\nただの小さい穴。明るすぎた訳ではない。\n深すぎたのだ。\n全てに、永遠に通じている。\n無限の選択肢を持つ穴。\n私は中を覗いてなどいなかった。\n外を覗いていた。\nそして彼が、向こう側から、中を覗いていた。\n"






























    old "But he wasn't looking at me.\nConfused, I frantically glance at my surroundings.\nBut my burned eyes can no longer see color.\nAre there others in this room? Are they talking?\nOr are they simply poems on flat sheets of paper,\nThe sound of frantic scrawling playing tricks on my ears?\nThe room begins to crinkle.\nClosing in on me.\nThe air I breathe dissipates before it reaches my lungs.\nI panic. There must be a way out.\nIt's right there. He's right there.\nSwallowing my fears, I brandish my pen."
    new "だが彼は私を見てはいなかった。\n混乱した私は、必死に辺りを見回す。\nでも、私の焼けた眼ではもはや色すら分からない。\n誰かこの部屋にいるの？話しているの？\nそれとも単に紙上に詩を綴っていて、\nそのペンを滑らせ奏でる狂った音色が私の耳に悪さしているの？\n部屋に皺が走る。\n私に迫る。\n私の吸った空気が、肺に到達する前に霧散する。\n戦慄する。ここから出なければ。\nすぐそこに。彼はすぐそこに。\n恐怖を飲み込んで、私はペンを振りかざした。"

























    old "Save Me"
    new "私をセーブして"

    old "The colors, they won't stop.\nBright, beautiful colors\nFlashing, expanding, piercing\nRed, green, blue\nAn endless\ncacophany\nOf meaningless\nnoise\nThe noise, it won't stop.\nViolent, grating waveforms\nSqueaking, screeching, piercing\nSine, cosine, tangent\n    Like playing a chalkboard on a turntable\n        Like playing a vinyl on a pizza crust\nAn endless\npoem\nOf meaningless\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nLoad Me\n    "
    new "止めどない色。\nまばゆく、綺麗な色が\n輝き、膨らみ、つんざく\n赤、緑、青\n止まない\n不協和音\n意味のない\n雑音\n止めどない雑音。\n荒々しく、耳障りな波形が\n軋み、叫び、つんざく\nサイン、コサイン、タンジェント\n　　ターンテーブルの上で黒板を奏でるように\n　　　　ピザ生地の上でレコードを奏でるように\n止まない\n詩\n意味のない\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n私をロードして\n　"







































    old "The colors, they won't\nBright, bea t ful c l rs\nFlash ng, exp nd ng, piercing\nRed, green, blue\nAn  ndless\nCACOPHANY\nOf meaningless\nnoise\nThe noise, it won't STOP.\nViol nt, grating w vef rms\nSq e king, screech ng, piercing\nSINE, COSINE, TANGENT\n    Like play ng a ch lkboard on a t rntable\n        Like playing a KNIFE on a BREATHING RIBCAGE\n n  ndl ss\np  m\nOf m  n ngl ss\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDelete Her\n    "
    new "止めどな　色。\nまばゆく、綺　な　が\n　き、膨ら　、つんざく\n赤、緑、青\n止　ない\n不　協　和　音\n意味のない\n雑音\n止 め ど ない雑音。\n荒　しく、耳障り　　形が\n　み　叫　、つんざく\nSINE、COSINE、TANGENT\n　　ター　テー　ルの上で黒　　奏　るように\n　　　　ナ イ フ で 胸 郭 の 喘 ぎ を奏でるように\n　　ない\n詩\n意　のな　\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n彼女を消して\n　"







































    old "The Lady who Knows Everything"
    new "全てを知る女性"

    old "An old tale tells of a lady who wanders Earth.\nThe Lady who Knows Everything.\nA beautiful lady who has found every answer,\nAll meaning,\nAll purpose,\nAnd all that was ever sought.\nAnd here I am,\n              a feather\nLost adrift the sky, victim of the currents of the wind.\nDay after day, I search.\nI search with little hope, knowing legends don't exist.\nBut when all else has failed me,\nWhen all others have turned away,\nThe legend is all that remains - the last dim star glimmering in the twilit sky.\nUntil one day, the wind ceases to blow.\nI fall.\nAnd I fall and fall, and fall even more.\nGentle as a feather.\nA dry quill, expressionless.\nBut a hand catches me between the thumb and forefinger.\nThe hand of a beautiful lady.\nI look at her eyes and find no end to her gaze.\nThe Lady who Knows Everything knows what I am thinking.\nBefore I can speak, she responds in a hollow voice.\n\"I have found every answer, all of which amount to nothing.\nThere is no meaning.\nThere is no purpose.\nAnd we seek only the impossible.\nI am not your legend.\nYour legend does not exist.\"\nAnd with a breath, she blows me back afloat, and I pick up a gust of wind."
    new "地上のどこかを渡り歩く女性の、古い言い伝え。\n全てを知る女性。\n全ての真理を突き止めた美しい女性。\n全ての意味を、\n全ての目的を、\n今まで抱えて来た全ての望みを。\nそして、私は一枚の\n　　　　　　　羽根\n風の流れのままに、宙をたゆたう。\n日毎夜毎に、探し求める。\n伝説など在り得ないと悟りながら、暗い先行きの中を探し求める。\nそれでも何もかもが過ちで、\n誰もかもが見放した時には、\n最早伝説しか残されていない――薄明の空に紛れる最後の星影なのだ。\nついにある日、風が凪いだ。\n私は降りる。\n降りて降りて、いつまでも降りていく。\n羽根のような静けさで。\n乾いた羽軸は無機質に。\nだが、親指と人差し指が私を摘む。\n美しい女性の手。\n彼女の瞳を見ると、その視線は途方もない。\n全てを知る女性は私の考えていることを知っている。\n私が物を言う前に、虚ろな声で彼女は答えた。\n「私は全ての真理を得ましたが、どれもこれも存在しなかったのです。\n意味など存在しない。\n目的など存在しない。\n私たちが望むのはいつだって実現し得ないもの。\n私はあなたの伝説ではありません。\nあなたの伝説は在り得ません。」\nそして彼女が息を吹きかけると再び宙を舞い、一陣の風が私を連れ去る。"































































    old "Happy End"
    new "ハッピーエンド"

    old "Pen in hand, I find my strength.\nThe courage endowed upon me by my one and only love.\nTogether, let us dismantle this crumbling world\nAnd write a novel of our own fantasies.\nWith a flick of her pen, the lost finds her way.\nIn a world of infinite choices, behold this special day.\nAfter all,\nNot all good times must come to an end."
    new "ペンを手に取り、自分の力を見出す。\n勇気は私にただ一つの愛を授けた。\n一緒に、こんな壊滅した世界は断ち切って\n私たちのファンタジーを綴って行きましょう。\nペンの一振りで、失ったものが彼女の元へ辿り着く。\n無限の選択肢が連なる世界で、出会えたこの特別な日を見届けて。\nやっぱり、\n楽しい時間に限りがあるというのは、例外もあるのね。"
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
